spring.application.name=nogiquiz

# DB
spring.datasource.url: jdbc:mysql://database-2.c38q8qkaiywk.ap-northeast-1.rds.amazonaws.com:3306/nogiquiz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=koizumi
spring.datasource.password=koi123
spring.sql.init.mode=never

# Message
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false