CREATE TABLE m_prefecture (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE m_bloodtype (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(10) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE m_generation (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE m_category (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(20) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE m_member (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
birthday DATE NOT NULL,
bloodtype_id BIGINT NOT NULL,
prefecture_id BIGINT NOT NULL,
generation_id BIGINT NOT NULL,
is_active TINYINT(1) NOT NULL,
FOREIGN KEY (bloodtype_id) REFERENCES m_bloodtype(id),
FOREIGN KEY (prefecture_id) REFERENCES m_prefecture(id),
FOREIGN KEY (generation_id) REFERENCES m_generation(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE m_player(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL UNIQUE,
password CHAR(60) NOT NULL,
loggedin_at DATETIME(6) DEFAULT NULL,
role VARCHAR(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE t_score (
id BIGINT AUTO_INCREMENT PRIMARY KEY,
is_active TINYINT(1) NOT NULL,
category_id BIGINT NOT NULL,
score INT NOT NULL,
player_id BIGINT NOT NULL,
played_at DATETIME(6) NOT NULL,
FOREIGN KEY (category_id) REFERENCES m_category(id),
FOREIGN KEY (player_id) REFERENCES m_player(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

